FROM node:20-alpine

WORKDIR /app

COPY package.json .
COPY scripts/ ./scripts/
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 8081
EXPOSE 19000
EXPOSE 19001

ENV EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

CMD ["npx", "expo", "start", "--port", "8081"]
